In [2]:
!pip install numpy


  Using cached numpy-2.4.3-cp313-cp313-win_amd64.whl.metadata (6.6 kB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ----------------

In [4]:
import numpy as np

# CREATING ARRAY FROM LIST

In [13]:
# 1d array

In [5]:
list=[1,2,3,4]
arr=np.array(list)
print(f"array is : {arr} , datatype ={type(arr)}")

array is : [1 2 3 4] , datatype =<class 'numpy.ndarray'>


In [14]:
# 2d array

In [12]:
list1=[[1,2,3,4],[11,12,13,14]]
print(list1)

[[1, 2, 3, 4], [11, 12, 13, 14]]


# CREATING ARRAY FROM TUPLE

In [6]:
tuple1=(1,2,3,4)
arr=np.array(tuple1)
print(arr)

[1 2 3 4]


# CREATING ARRAY FROM SET 

In [17]:
my_set={1,2,3,4,5}
arr=np.array(my_set) # it will be in set not in array 
print(arr)

{1, 2, 3, 4, 5}


In [17]:
list1=[[1,2,3,4],[11,12,13,14]]
arr=np.array(list1)
print(arr)
my_array=np.array([[1,2,3,4],[11,12,13,14]])
print(my_array)

[[ 1  2  3  4]
 [11 12 13 14]]
[[ 1  2  3  4]
 [11 12 13 14]]


# linspace ,,,arange

In [23]:
arr3=np.linspace(0,30,5)
print(arr3)
arr4=np.arange(0,30,3)    
print(arr4)

[ 0.   7.5 15.  22.5 30. ]
[ 0  3  6  9 12 15 18 21 24 27]


In [23]:
l=[1,2]
print(l*2)    # list multiplication
arr=np.array(l) # array multiplication
print(arr*2)

[1, 2, 1, 2]
[2 4]


In [1]:
import time
current_time=time.time()
print(current_time)

1774523785.4798455


### make the array my_array

In [22]:
my_array=np.array([[1,23,56,6],[2,4,6,8],[22,33,44,55]] , dt)
print(my_array)

[[ 1 23 56  6]
 [ 2  4  6  8]
 [22 33 44 55]]


### List vs numpy array

In [24]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

Python list multiplication  [1, 2, 3, 1, 2, 3]


In [25]:
np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

Python array multiplication  [2 4 6]


# time library

In [34]:
import time

start=time.time()

py_list=[i*2 for i in range(10000)]
print(time.time()-start)

start=time.time()

np_array=np.arange(10000)*2
print(time.time()-start)



0.0006287097930908203
0.0005664825439453125


# CREATING ARRAY FROM SCRATCH

In [37]:
# array of 0's

In [36]:
arr=np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [38]:
# ones

In [40]:
arr=np.ones((4,4))  ((rows,columns))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [41]:
# full array

In [42]:
arr=np.full((4,4),8)   (rows,columns),value
print(arr)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [50]:
# random

In [49]:
arr=np.random.random((2,4))

arrr=np.random.rand(2,4)

print(arr)
print("")
print(arrr)

[[0.5104889  0.97266406 0.54010669 0.16021397]
 [0.69332937 0.46460515 0.39394895 0.34313211]]

[[0.6291833  0.54247107 0.51557765 0.36621513]
 [0.30990214 0.38059286 0.2044515  0.86836036]]
[[0.5104889  0.97266406 0.54010669 0.16021397]
 [0.69332937 0.46460515 0.39394895 0.34313211]]


In [51]:
eye=np.eye(4)
print(eye)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# ARRAY ATTRIBUTES

In [53]:
a = np.array([[1, 2, 3], [4, 5.5, 6]])
print(a)
print("Shape:", a.shape)       # (2, 3)
print("Size:", a.size)         # 6
print("Dimensions:", a.ndim)   # 2
print("Data type:", a.dtype) 

[[1.  2.  3. ]
 [4.  5.5 6. ]]
Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: float64


# VECTOR, MATRIX,TENSOR

In [66]:
#1d array=vector
#2d array=matrix
#nd array=tensor
vector=np.array([1,2,3])
print(vector)

matrix=np.array([[1,2,3],[4,5,6]])
print("matrix is :\n" , matrix)


#tensor

tensor=np.array([[1,2,3],[4,5,6],[7,5,9]])
print("tensor is :\n",tensor)


#tensor 

tensor1=np.array([[[1,2,3],[4,5,6],[6,7,8]],[[1,23,4],[55,77,66],[99,66,44]]])
print("Tensor is \n\n",tensor1)

[1 2 3]
matrix is :
 [[1 2 3]
 [4 5 6]]
tensor is :
 [[1 2 3]
 [4 5 6]
 [7 5 9]]
Tensor is 

 [[[ 1  2  3]
  [ 4  5  6]
  [ 6  7  8]]

 [[ 1 23  4]
  [55 77 66]
  [99 66 44]]]


# ARRAY RESHAPING

In [77]:
arr=np.arange(12)
print(arr)
print(arr.shape)

reshaped=arr.reshape((3,4))
print(reshaped)

flattened=reshaped.flatten()
print("\n",flattened)

raveled=reshaped.ravel()
print(raveled)

transpose=reshaped.T
print("\n",transpose)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 [ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]

 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


# Task #1 :

In [79]:
ary=np.random.random((4,4))
print(ary)
mean_ary=np.mean(ary)
print("mean  is :" , mean_ary)
maximum=np.max(ary)
print("max is : ", maximum)


[[0.32195231 0.87583247 0.36170196 0.66367634]
 [0.35698717 0.34123001 0.56913696 0.76513802]
 [0.6711295  0.70586189 0.19098892 0.93706674]
 [0.4162512  0.91492046 0.05433389 0.91035137]]
mean  is : 0.5660349513067549
max is :  0.9370667389411547


# TASK #2

In [81]:
arr=np.arange(10)
print(arr)
reshaped=arr.reshape(2,5)
print("Reshaped array is \n ", reshaped)

[0 1 2 3 4 5 6 7 8 9]
Reshaped array is 
  [[0 1 2 3 4]
 [5 6 7 8 9]]


# TASK 3

In [83]:
matrix=np.array([[1,2,3,4],
                 [10,20,30,40],
                 [50,60,70,80],
                 [90,30,69,90]
                ])
row_vector=np.array([100,200,300,400])
addition=matrix+row_vector

print("addition is :" ,addition)

addition is : [[101 202 303 404]
 [110 220 330 440]
 [150 260 370 480]
 [190 230 369 490]]
